# Generated by Django 5.2.8 on 2025-11-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the location', max_length=255, unique=True)),
                ('address', models.CharField(blank=True, help_text='The address of the location', max_length=255, null=True)),
                ('coordinates', models.CharField(blank=True, help_text='The coordinates of the location', max_length=255, null=True)),
            ],
        ),
    ]
